# From https://github.com/vnc-tools/debug-on-mac.
#
# Set up the server for a VNC connection via ngrok.
name: macos_vnc
on:
  workflow_dispatch:
    inputs:
      vnc_user_password:
        description: Password for the created user (vncuser)
        required: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          VNC_USER_PASSWORD: ${{ github.event.inputs.vnc_user_password }}
          VNC_PASSWORD: ${{ github.event.inputs.vnc_user_password }}
        run: source .github/macos_vnc.sh "$VNC_USER_PASSWORD" "$VNC_PASSWORD" "$NGROK_AUTH_TOKEN"

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Ableton Live
        run: brew install --cask ableton-live-lite

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip

      - run: python -m pip install poetry
      - run: poetry install

      - name: ngrok is now listening to VNC connections on...
        run: curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
