---
name: validate
on:
  pull_request:
    branches: [master]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2-dev
          version: 1.0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: make lint
