---
name: validate
on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2-dev
          version: 1.0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip
      - run: python -m pip install poetry
      - run: poetry install
      - run: make lint

  check-types:
    runs-on: macos-13
    timeout-minutes: 30
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Ableton Live
        run: brew install --cask ableton-live-lite

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip

      - run: python -m pip install poetry
      - run: poetry install
      - run: make check
