---
name: validate
on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2-dev
          version: 1.0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - run: python -m pip install poetry
      - run: make install
      - run: make lint

  check-types:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2-dev
          version: 1.0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - run: python -m pip install poetry
      - run: make install
      - run: make check

  release:
    name: Publish release to GitHub
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: release
    environment:
      name: release

    if: github.event_name == 'push'

    # Make sure everything else succeeds before releasing.
    needs:
      - lint
      - check-types

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Semantic Release
        uses: python-semantic-release/python-semantic-release@v9.8.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
